/* EventSphere Event Management Database Schema

Script 2.2: Inserting the values in Organization Table
Created by: Arpita Deb
Dated: 2024-09-08 12:55:09.127
About: DML Commands to insert values in the  Organization Table

*/
-- Initiating the database
USE [EventSphere Database];

-- 2.Organization 

insert into Organization (name, contact_person, email, phone) values ('Muller-Corwin', 'Myrwyn Ipsley', 'mipsley0@toplist.cz', '+258 956 290 6798');
insert into Organization (name, contact_person, email, phone) values ('Hackett, Schuster and Witting', 'Cherye Daniel', 'cdaniel1@umich.edu', '+62 283 811 6677');
insert into Organization (name, contact_person, email, phone) values ('Rohan-Beahan', 'Elena Jozsika', 'ejozsika2@google.co.uk', '+63 383 509 6628');
insert into Organization (name, contact_person, email, phone) values ('Franecki, Ledner and Lueilwitz', 'Jud Sibly', 'jsibly3@vkontakte.ru', '+375 901 923 6048');
insert into Organization (name, contact_person, email, phone) values ('Miller and Sons', 'Maury Kerne', 'mkerne4@wikimedia.org', '+212 285 167 4709');
insert into Organization (name, contact_person, email, phone) values ('Blick-Langosh', 'Oliviero Crees', 'ocrees5@ucsd.edu', '+994 516 212 4766');
insert into Organization (name, contact_person, email, phone) values ('Hickle-Brakus', 'Mahala Macartney', 'mmacartney8@ustream.tv', '+57 999 229 2876');
insert into Organization (name, contact_person, email, phone) values ('Metz, Nicolas and Greenfelder', 'Dorothy Boyack', 'dboyack9@microsoft.com', null);
insert into Organization (name, contact_person, email, phone) values ('Larkin Inc', 'Leigha Rivallant', 'lrivallanta@privacy.gov.au', '+48 801 578 9264');
insert into Organization (name, contact_person, email, phone) values ('Beahan Group', 'Susannah Matteoni', 'smatteonib@noaa.gov', '+48 864 713 9975');
insert into Organization (name, contact_person, email, phone) values ('Jones, Champlin and Blanda', 'Jeremie Sheeran', 'jsheeranc@rakuten.co.jp', '+55 255 322 0762');
insert into Organization (name, contact_person, email, phone) values ('Bogan, Beer and Daniel', 'Town Dalston', 'tdalstond@illinois.edu', '+66 642 800 2150');
insert into Organization (name, contact_person, email, phone) values ('Lehner, Ullrich and Gerlach', 'Ella Cure', 'ecuree@bravesites.com', '+62 807 152 2249');
insert into Organization (name, contact_person, email, phone) values ('Emard Inc', 'Mercie Whiscard', 'mwhiscardf@army.mil', '+62 827 485 2414');
insert into Organization (name, contact_person, email, phone) values ('Hilll-Abernathy', 'Wilmer de Werk', 'wdeg@dot.gov', '+86 483 774 2195');
insert into Organization (name, contact_person, email, phone) values ('Kihn Group', 'Sydelle Westmarland', 'swestmarlandh@google.es', null);
insert into Organization (name, contact_person, email, phone) values ('Wyman Inc', 'Aubine Bonhome', 'abonhomei@sogou.com', '+86 542 172 6587');
insert into Organization (name, contact_person, email, phone) values ('Kutch-Jerde', 'Ann-marie Snel', 'asnelj@storify.com', '+57 232 223 2312');
insert into Organization (name, contact_person, email, phone) values ('Sauer Group', 'Hew Eaglesham', 'heagleshamk@alibaba.com', null);
insert into Organization (name, contact_person, email, phone) values ('Runolfsson, Altenwerth and Wunsch', 'Linea Schubbert', 'lschubbertl@google.it', '+62 125 188 6165');
insert into Organization (name, contact_person, email, phone) values ('Hettinger and Sons', 'Pooh Hovington', 'phovingtonm@vinaora.com', '+261 640 799 5530');
insert into Organization (name, contact_person, email, phone) values ('Reichert, Kohler and Schaefer', 'Jamie Romagnosi', 'jromagnosin@bizjournals.com', '+48 552 698 6449');
insert into Organization (name, contact_person, email, phone) values ('Braun and Sons', 'Cher Presidey', 'cpresideyo@shinystat.com', null);
insert into Organization (name, contact_person, email, phone) values ('Windler LLC', 'Dixie Ahern', 'dahernp@instagram.com', '+86 342 298 3614');
insert into Organization (name, contact_person, email, phone) values ('Cremin Inc', 'Krissie Anger', 'kangerq@lycos.com', '+86 938 586 8615');
insert into Organization (name, contact_person, email, phone) values ('Legros, Kovacek and Kozey', 'Bernie Rattenbury', 'brattenburyr@amazon.co.jp', '+82 941 464 2805');
insert into Organization (name, contact_person, email, phone) values ('Schamberger LLC', 'Chalmers Eykelhof', 'ceykelhofs@ebay.com', '+967 237 446 4234');
insert into Organization (name, contact_person, email, phone) values ('Armstrong Inc', 'Layla Crannage', 'lcrannaget@dailymail.co.uk', '+86 266 292 8938');
insert into Organization (name, contact_person, email, phone) values ('Beer, Koelpin and Stokes', 'Griffie Giacobbo', 'ggiacobbou@usatoday.com', null);
insert into Organization (name, contact_person, email, phone) values ('Rath-Mayer', 'Clemmie Looney', 'clooneyw@huffingtonpost.com', '+7 862 470 3906');
insert into Organization (name, contact_person, email, phone) values ('Cremin, Dickens and Funk', 'Hughie Philipsson', 'hphilipssonx@slate.com', '+49 705 997 1998');
insert into Organization (name, contact_person, email, phone) values ('Rosenbaum-Auer', 'Gerrilee Dudill', 'gdudillz@telegraph.co.uk', '+351 568 169 2146');
insert into Organization (name, contact_person, email, phone) values ('Lindgren-Hilll', 'Sumner Wohler', 'swohler11@ftc.gov', '+86 613 104 7829');
insert into Organization (name, contact_person, email, phone) values ('Kertzmann, Gutkowski and King', 'Miguel Hatchman', 'mhatchman12@comcast.net', '+46 413 539 6979');
insert into Organization (name, contact_person, email, phone) values ('King and Sons', 'Sig Balsdon', 'sbalsdon14@gizmodo.com', null);
insert into Organization (name, contact_person, email, phone) values ('Welch, Lang and Treutel', 'Rad Giampietro', 'rgiampietro15@so-net.ne.jp', '+351 515 441 4701');
insert into Organization (name, contact_person, email, phone) values ('Donnelly-Marks', 'Annnora Pauer', 'apauer16@taobao.com', '+48 317 607 9385');
insert into Organization (name, contact_person, email, phone) values ('Bogan, Gleason and Lindgren', 'Carmella Szantho', 'cszantho1a@walmart.com', '+380 263 306 8598');
insert into Organization (name, contact_person, email, phone) values ('Fritsch-Wolff', 'Daven Broughton', 'dbroughton1b@sphinn.com', '+62 100 844 6477');
insert into Organization (name, contact_person, email, phone) values ('Wisoky-Morissette', 'Emily Assante', 'eassante1c@businessweek.com', null);
insert into Organization (name, contact_person, email, phone) values ('Shields, Gibson and Thompson', 'Reggie Patters', 'rpatters1d@typepad.com', null);
insert into Organization (name, contact_person, email, phone) values ('Goldner-Greenholt', 'Alyce Vignal', 'avignal1f@phpbb.com', '+46 146 213 8313');
insert into Organization (name, contact_person, email, phone) values ('Feil, Bailey and Swaniawski', 'Shellie Tinline', 'stinline1h@51.la', '+237 644 696 5958');
insert into Organization (name, contact_person, email, phone) values ('Nolan, Hagenes and Marquardt', 'Regan Bowhey', 'rbowhey1i@wufoo.com', '+63 419 435 8041');
insert into Organization (name, contact_person, email, phone) values ('Willms Group', 'Demetrius Scrafton', 'dscrafton1j@blogs.com', null);
insert into Organization (name, contact_person, email, phone) values ('Reichert, Feil and Prosacco', 'Jehu Bines', 'jbines1k@purevolume.com', '+62 137 840 3970');
insert into Organization (name, contact_person, email, phone) values ('Murazik LLC', 'Carroll Julien', 'cjulien1m@gnu.org', '+30 715 812 7559');
insert into Organization (name, contact_person, email, phone) values ('Cronin-Greenholt', 'Cris Vigars', 'cvigars1n@webs.com', '+86 971 144 9555');
insert into Organization (name, contact_person, email, phone) values ('Rippin-Frami', 'Deck Aery', 'daery1o@wsj.com', '+86 413 406 7043');
insert into Organization (name, contact_person, email, phone) values ('Kertzmann and Sons', 'Wilbur Ricard', 'wricard1p@google.co.jp', '+62 807 854 9563');
insert into Organization (name, contact_person, email, phone) values ('Deckow Group', 'Mischa Lambertini', 'mlambertini1r@tmall.com', '+86 404 311 2923');
insert into Organization (name, contact_person, email, phone) values ('Abernathy-Hahn', 'Jonis Monnoyer', 'jmonnoyer1s@patch.com', '+62 518 848 6878');
insert into Organization (name, contact_person, email, phone) values ('Ullrich, Keebler and Roberts', 'Corinne Selliman', 'cselliman1t@ted.com', '+62 855 591 3482');
insert into Organization (name, contact_person, email, phone) values ('White, Feest and Hermann', 'Delphine Elderidge', 'delderidge1u@diigo.com', '+86 810 741 0187');
insert into Organization (name, contact_person, email, phone) values ('Wyman, Grady and Towne', 'Audry De Malchar', 'ade1v@merriam-webster.com', '+7 862 791 2692');
insert into Organization (name, contact_person, email, phone) values ('Hauck-Boyer', 'Shanda Gatehouse', 'sgatehouse1w@chron.com', '+86 187 657 2672');
insert into Organization (name, contact_person, email, phone) values ('Powlowski LLC', 'Dukey Dymidowski', 'ddymidowski1x@de.vu', '+64 994 334 3189');
insert into Organization (name, contact_person, email, phone) values ('Hyatt-Wuckert', 'Daniella Doorey', 'ddoorey1y@ca.gov', '+55 572 529 6411');
insert into Organization (name, contact_person, email, phone) values ('Friesen-Mann', 'Ralf McGarahan', 'rmcgarahan1z@google.es', '+7 102 987 7608');
insert into Organization (name, contact_person, email, phone) values ('Wisoky-McLaughlin', 'Hale Winspeare', 'hwinspeare20@imgur.com', '+86 508 767 1904');
insert into Organization (name, contact_person, email, phone) values ('Stokes-Roberts', 'Isiahi Biggs', 'ibiggs21@a8.net', '+86 897 843 2319');
insert into Organization (name, contact_person, email, phone) values ('Cartwright, Schuster and Rodriguez', 'Heloise Alcott', 'halcott22@fc2.com', '+46 739 696 8396');
insert into Organization (name, contact_person, email, phone) values ('Rice-Collier', 'Jerri Ivanikhin', 'jivanikhin23@g.co', '+30 380 373 1261');
insert into Organization (name, contact_person, email, phone) values ('Huels, Paucek and Schiller', 'Hanson Janowski', 'hjanowski24@nytimes.com', '+31 787 944 2865');
insert into Organization (name, contact_person, email, phone) values ('Hansen-Kiehn', 'Kissie Ruckledge', 'kruckledge26@theatlantic.com', '+964 520 639 7024');
insert into Organization (name, contact_person, email, phone) values ('Crist LLC', 'Marthe Dixcey', 'mdixcey27@trellian.com', null);
insert into Organization (name, contact_person, email, phone) values ('Ullrich Inc', 'Morie Clee', 'mclee28@google.nl', '+86 532 775 6769');
insert into Organization (name, contact_person, email, phone) values ('Aufderhar Inc', 'Kienan Nutley', 'knutley29@github.com', '+7 244 777 2401');
insert into Organization (name, contact_person, email, phone) values ('Kertzmann-Dibbert', 'Traci Elmhurst', 'telmhurst2a@harvard.edu', '+1 450 747 6576');
insert into Organization (name, contact_person, email, phone) values ('Murray-Bernier', 'Redd Salvador', 'rsalvador2b@mit.edu', '+7 936 217 9206');
insert into Organization (name, contact_person, email, phone) values ('Mraz-Gibson', 'Liam Dowbekin', 'ldowbekin2c@prweb.com', '+351 494 806 4387');
insert into Organization (name, contact_person, email, phone) values ('Daniel-Borer', 'Isidoro Gilchrist', 'igilchrist2e@uol.com.br', '+56 766 346 7244');
insert into Organization (name, contact_person, email, phone) values ('Cummings, Waelchi and Adams', 'Natka Petyt', 'npetyt2g@vkontakte.ru', null);
insert into Organization (name, contact_person, email, phone) values ('Brakus-Wehner', 'Pippo Bowell', 'pbowell2h@topsy.com', '+375 614 992 0718');
insert into Organization (name, contact_person, email, phone) values ('Stiedemann and Sons', 'Nertie Strongitharm', 'nstrongitharm2j@dailymotion.com', '+33 594 405 6108');
insert into Organization (name, contact_person, email, phone) values ('Reynolds and Sons', 'Van McMains', 'vmcmains2l@nsw.gov.au', '+62 975 874 7097');
insert into Organization (name, contact_person, email, phone) values ('Padberg, Krajcik and Yost', 'Tandy Reynoollds', 'treynoollds2n@yahoo.co.jp', '+966 537 174 0052');
insert into Organization (name, contact_person, email, phone) values ('Yost Group', 'Theressa Garioch', 'tgarioch2o@php.net', '+33 980 265 2998');
insert into Organization (name, contact_person, email, phone) values ('Wilderman-Wilkinson', 'Norby Bruggeman', 'nbruggeman2p@twitpic.com', '+86 204 261 1995');
insert into Organization (name, contact_person, email, phone) values ('Howell, Hickle and Murazik', 'Hilton Saladino', 'hsaladino2q@stanford.edu', '+62 515 269 7249');
insert into Organization (name, contact_person, email, phone) values ('Abernathy-Johnston', 'Conn Dobkin', 'cdobkin2r@g.co', '+63 464 804 1244');
insert into Organization (name, email, phone) values ('Kuhic, Abbott and Erdman', 'growthorne20@cnet.com', '+7 817 930 6538');
insert into Organization (name, email, phone) values ('Nikolaus Group', 'emcane0@nhs.uk', '+351 313 397 0483');
insert into Organization (name, email, phone) values ('Moen-Daugherty', 'nmacinnes1@hibu.com', '+86 484 483 6888');
insert into Organization (name, email, phone) values ('Jacobs, Kessler and Hansen', 'rcollinson2@free.fr', null);
insert into Organization (name, email, phone) values ('Cruickshank, Sporer and Little', 'kdymock3@omniture.com', '+86 262 332 6744');
insert into Organization (name, email, phone) values ('Vandervort and Sons', 'bwordsley4@latimes.com', '+63 137 255 3873');
insert into Organization (name, email, phone) values ('Legros Inc', 'fepperson5@mit.edu', '+880 764 406 6655');
insert into Organization (name, email, phone) values ('Predovic and Sons', 'lgilkison6@wsj.com', '+86 603 133 8107');
insert into Organization (name, email, phone) values ('Gottlieb, Abbott and Walter', 'cfrancie7@unc.edu', '+62 346 890 7173');
insert into Organization (name, email, phone) values ('Kreiger, Predovic and Luettgen', 'bgalley8@arizona.edu', '+351 706 308 5037');
insert into Organization (name, email, phone) values ('Koss-Schimmel', 'jstrognell9@acquirethisname.com', '+86 425 474 6701');
insert into Organization (name, email, phone) values ('Bartell, Wehner and Cummings', 'istebbinga@geocities.com', null);
insert into Organization (name, email, phone) values ('Raynor-Waters', 'larnaudinb@wiley.com', '+850 239 352 0344');
insert into Organization (name, email, phone) values ('Greenfelder LLC', 'eabrahamowitczc@vinaora.com', '+351 779 276 4171');
insert into Organization (name, email, phone) values ('Carter-Walter', 'dfairpod@umich.edu', '+33 614 453 7705');
insert into Organization (name, email, phone) values ('Becker and Sons', 'phulburde@dedecms.com', '+995 788 779 1498');
insert into Organization (name, email, phone) values ('Murphy-Bins', 'mbaylief@stanford.edu', '+33 203 210 3123');
insert into Organization (name, email, phone) values ('Lowe-Hudson', 'ewardhawg@nydailynews.com', null);
insert into Organization (name, email, phone) values ('Barrows and Sons', 'amaysorh@baidu.com', '+86 427 978 1083');
insert into Organization (name, email, phone) values ('Roob, Schoen and Dickens', 'edilnoti@discuz.net', '+47 154 695 8165');
insert into Organization (name, email, phone) values ('Lesch-Ebert', 'qickowiczj@moonfruit.com', '+1 630 644 7371');
insert into Organization (name, email, phone) values ('Wintheiser-Bode', 'jrosenbergerk@webmd.com', '+33 104 329 2327');
insert into Organization (name, email, phone) values ('Wunsch, Barton and Hilll', 'apatrickl@nature.com', '+62 618 884 5908');
insert into Organization (name, email, phone) values ('Beatty, Davis and Tromp', 'abunningm@infoseek.co.jp', '+63 526 718 4663');
insert into Organization (name, email, phone) values ('Muller-Toy', 'ehuitsonn@dmoz.org', null);
insert into Organization (name, email, phone) values ('Prosacco, Rodriguez and Schimmel', 'ptubbleso@multiply.com', '+370 517 151 7351');
insert into Organization (name, email, phone) values ('Schoen, Bosco and Cronin', 'cseamansp@cdbaby.com', '+86 823 721 7279');
insert into Organization (name, email, phone) values ('Stokes, Buckridge and Wolff', 'ithreaderq@columbia.edu', '+98 535 674 3560');
insert into Organization (name, email, phone) values ('Nolan and Sons', 'mwealr@jiathis.com', '+62 675 274 6840');
insert into Organization (name, email, phone) values ('Renner Group', 'ttomasinis@mozilla.com', '+86 147 571 7594');
insert into Organization (name, email, phone) values ('Upton-Bernhard', 'rdeetht@godaddy.com', '+359 193 733 0849');
insert into Organization (name, email, phone) values ('Ryan, Nolan and Hamill', 'agreseru@walmart.com', '+7 673 947 1492');
insert into Organization (name, email, phone) values ('Conroy, Nolan and Altenwerth', 'pbubbinsv@squarespace.com', '+63 252 468 4024');
insert into Organization (name, email, phone) values ('Moore-Zboncak', 'cpitsonw@linkedin.com', '+245 694 408 4875');
insert into Organization (name, email, phone) values ('Denesik-Kshlerin', 'callistonx@stumbleupon.com', null);
insert into Organization (name, email, phone) values ('Wiegand Group', 'lgaginy@timesonline.co.uk', '+62 844 749 6062');
insert into Organization (name, email, phone) values ('West, Rosenbaum and Simonis', 'mmitchensonz@facebook.com', '+86 745 334 3198');
insert into Organization (name, email, phone) values ('Adams Inc', 'lsollime10@marriott.com', '+62 220 965 0168');
insert into Organization (name, email, phone) values ('Upton, Rogahn and Waelchi', 'lguinane11@yale.edu', '+261 897 829 6104');
insert into Organization (name, email, phone) values ('Mills, Hansen and Cormier', 'lcozins12@istockphoto.com', '+30 960 918 9128');
insert into Organization (name, email, phone) values ('Bruen-Streich', 'gshyram13@answers.com', '+358 779 154 2900');
insert into Organization (name, email, phone) values ('Stoltenberg Group', 'dcadwell14@ucoz.ru', '+33 901 898 2852');
insert into Organization (name, email, phone) values ('Goodwin-Harvey', 'lmoen15@ehow.com', '+62 980 538 0406');
insert into Organization (name, email, phone) values ('Ritchie Inc', 'msinkings16@census.gov', '+86 126 378 8339');
insert into Organization (name, email, phone) values ('McDermott-Fadel', 'theggs17@china.com.cn', '+86 793 470 8703');
insert into Organization (name, email, phone) values ('Mitchell Group', 'msprigging18@amazon.de', '+1 616 663 9229');
insert into Organization (name, email, phone) values ('Johnson, Brekke and Gottlieb', 'mairy19@spotify.com', null);
insert into Organization (name, email, phone) values ('Medhurst-Mayer', 'akerrod1a@geocities.com', '+86 930 309 6349');
insert into Organization (name, email, phone) values ('Kozey LLC', 'gscotchmore1b@pagesperso-orange.fr', null);
insert into Organization (name, email, phone) values ('Mills Group', 'pkorfmann1c@admin.ch', '+33 184 715 0597');
insert into Organization (name, email, phone) values ('Howell Group', 'shoudmont1d@skyrock.com', '+7 780 247 5069');
insert into Organization (name, email, phone) values ('Brakus LLC', 'bmarie1e@shareasale.com', '+53 111 655 6897');
insert into Organization (name, email, phone) values ('Koepp, Feest and Hermann', 'jlewerenz1f@businessweek.com', '+591 988 557 5600');
insert into Organization (name, email, phone) values ('O''Hara-Toy', 'jeastment1g@redcross.org', '+86 790 960 6173');
insert into Organization (name, email, phone) values ('Crist Group', 'fboribal1h@fc2.com', '+66 331 791 8036');
insert into Organization (name, email, phone) values ('Will, Lemke and Doyle', 'pclaque1i@cargocollective.com', '+62 995 293 0528');
insert into Organization (name, email, phone) values ('Reynolds Inc', 'smarzelle1j@weibo.com', '+86 592 947 8195');
insert into Organization (name, email, phone) values ('Cummings-Schowalter', 'drozec1k@barnesandnoble.com', '+81 106 332 2385');
insert into Organization (name, email, phone) values ('Ratke, Brakus and Schulist', 'fjerrand1l@amazon.co.jp', null);
insert into Organization (name, email, phone) values ('Hirthe and Sons', 'kfalls1m@rediff.com', '+375 827 724 3166');
insert into Organization (name, email, phone) values ('Kirlin-Hane', 'tminthorpe1n@e-recht24.de', '+1 342 626 4465');
insert into Organization (name, email, phone) values ('Conroy-Beer', 'dboake1o@amazonaws.com', '+86 695 818 7182');
insert into Organization (name, email, phone) values ('Marks Inc', 'mmatteoli1p@google.com.hk', '+351 345 595 7841');
insert into Organization (name, email, phone) values ('Champlin-Upton', 'abakster1q@arizona.edu', '+62 324 635 2558');
insert into Organization (name, email, phone) values ('Hammes-Jones', 'gcamin1r@quantcast.com', '+7 141 192 1113');
insert into Organization (name, email, phone) values ('Johns and Sons', 'bhebdon1s@sogou.com', '+33 683 261 6667');
insert into Organization (name, email, phone) values ('Kuphal, Bechtelar and Kautzer', 'lstaite1t@irs.gov', '+63 176 574 0226');
insert into Organization (name, email, phone) values ('Greenfelder and Sons', 'arolland1u@hugedomains.com', '+7 970 386 2933');
insert into Organization (name, email, phone) values ('Ernser-Connelly', 'eoutlaw1v@addtoany.com', '+1 205 870 5088');
insert into Organization (name, email, phone) values ('Russel-Wintheiser', 'ychamberlain1w@slideshare.net', '+7 171 605 8364');
insert into Organization (name, email, phone) values ('Walsh LLC', 'ygorman1x@squarespace.com', '+58 124 109 1643');
insert into Organization (name, email, phone) values ('Kozey Group', 'pmattersley1y@macromedia.com', '+963 267 643 8166');
insert into Organization (name, email, phone) values ('Hammes-Hintz', 'pskellington1z@domainmarket.com', null);

SELECT * FROM  Organization;
