/* EventSphere Event Management Database Schema

Script 2.3: Inserting the values in Partner Table
Created by: Arpita Deb
Dated: 2024-09-08 12:55:09.127
About: DML Commands to insert values in the  Partner Table

*/
-- Initiating the database
USE [EventSphere Database];

-- 3. Partner

insert into Partner (name, email, phone) values ('Brita MacCurley', 'bmaccurley0@wordpress.com', null);
insert into Partner (name, email, phone) values ('Barron Bathurst', 'bbathurst1@over-blog.com', '+86 747 713 7923');
insert into Partner (name, email, phone) values ('Taffy Crozier', 'tcrozier2@blogspot.com', '+972 387 774 9112');
insert into Partner (name, email, phone) values ('Beatrice Blaxall', 'bblaxall3@163.com', '+86 562 734 1936');
insert into Partner (name, email, phone) values ('Fairleigh Hryniewicki', 'fhryniewicki4@upenn.edu', '+66 628 967 8265');
insert into Partner (name, email, phone) values ('Gillan Hadden', 'ghadden5@cloudflare.com', '+86 843 285 9904');
insert into Partner (name, email, phone) values ('Toby Castelyn', 'tcastelyn6@github.com', '+86 920 913 6138');
insert into Partner (name, email, phone) values ('Renaldo Pinching', 'rpinching7@printfriendly.com', '+7 499 781 1633');
insert into Partner (name, email, phone) values ('Ambur De Gowe', 'ade8@businessinsider.com', '+507 766 853 6541');
insert into Partner (name, email, phone) values ('Ellswerth Wroath', 'ewroath9@geocities.com', null);
insert into Partner (name, email, phone) values ('Nara Robker', 'nrobkera@google.de', '+62 614 271 7155');
insert into Partner (name, email, phone) values ('Kristoforo Davis', 'kdavisb@smh.com.au', null);
insert into Partner (name, email, phone) values ('Bjorn Trowsdale', 'btrowsdalec@economist.com', '+389 697 928 5905');
insert into Partner (name, email, phone) values ('Simone Jiggle', 'sjiggled@oakley.com', '+33 121 144 5257');
insert into Partner (name, email, phone) values ('Juana Colqueran', 'jcolquerane@stanford.edu', '+46 960 461 9168');
insert into Partner (name, email, phone) values ('Alphonso Di Dello', 'adif@hubpages.com', '+55 392 771 4283');
insert into Partner (name, email, phone) values ('Marcelo Luker', 'mlukerg@kickstarter.com', '+81 160 727 4869');
insert into Partner (name, email, phone) values ('Viva Joiner', 'vjoinerh@cnn.com', '+261 673 192 1236');
insert into Partner (name, email, phone) values ('Lani Kidder', 'lkidderi@jimdo.com', '+46 338 594 6081');
insert into Partner (name, email, phone) values ('Perri Penas', 'ppenasj@devhub.com', '+52 401 499 8162');
insert into Partner (name, email, phone) values ('Ada Maskew', 'amaskewk@cyberchimps.com', '+967 952 569 2998');
insert into Partner (name, email, phone) values ('Tomkin Reicharz', 'treicharzl@ox.ac.uk', null);
insert into Partner (name, email, phone) values ('Salli Toderini', 'stoderinim@goo.gl', '+7 162 872 5801');
insert into Partner (name, email, phone) values ('Jack Tolerton', 'jtolertonn@nasa.gov', '+55 712 296 8681');
insert into Partner (name, email, phone) values ('Murvyn Killcross', 'mkillcrosso@state.gov', '+86 454 770 7591');
insert into Partner (name, email, phone) values ('Alaric Coston', 'acostonp@apache.org', null);
insert into Partner (name, email, phone) values ('Roy Cunnow', 'rcunnowq@wikipedia.org', '+1 220 846 3752');
insert into Partner (name, email, phone) values ('Amil Boak', 'aboakr@pagesperso-orange.fr', '+62 671 988 4414');
insert into Partner (name, email, phone) values ('Rey Proby', 'rprobys@rambler.ru', '+62 579 859 9035');
insert into Partner (name, email, phone) values ('Magdalene Daughton', 'mdaughtont@spotify.com', '+62 312 220 7280');
insert into Partner (name, email, phone) values ('Bronnie Saffill', 'bsaffillu@europa.eu', '+48 363 312 0508');
insert into Partner (name, email, phone) values ('Joelynn Emmitt', 'jemmittv@facebook.com', '+62 617 353 2511');
insert into Partner (name, email, phone) values ('Schuyler Bilbey', 'sbilbeyw@google.com', '+880 546 977 9720');
insert into Partner (name, email, phone) values ('Othelia Locksley', 'olocksleyx@slashdot.org', '+20 878 197 1219');
insert into Partner (name, email, phone) values ('Teodorico Jerisch', 'tjerischy@phoca.cz', '+86 338 862 0201');
insert into Partner (name, email, phone) values ('Shanan Ochterlony', 'sochterlonyz@ask.com', '+30 551 348 5919');
insert into Partner (name, email, phone) values ('Lizbeth Sansome', 'lsansome10@php.net', null);
insert into Partner (name, email, phone) values ('Susie Trevaskus', 'strevaskus11@answers.com', '+55 221 354 8661');
insert into Partner (name, email, phone) values ('Lukas Hebner', 'lhebner12@vistaprint.com', '+62 545 130 2506');
insert into Partner (name, email, phone) values ('Lucian Costi', 'lcosti13@java.com', '+62 292 711 5283');
insert into Partner (name, email, phone) values ('Tabbie Bobasch', 'tbobasch14@lulu.com', null);
insert into Partner (name, email, phone) values ('Jordain Dignam', 'jdignam15@smh.com.au', '+86 711 509 7552');
insert into Partner (name, email, phone) values ('Shayne Blamey', 'sblamey16@biblegateway.com', '+675 815 597 0838');
insert into Partner (name, email, phone) values ('Carlina O''Rowane', 'corowane17@yolasite.com', null);
insert into Partner (name, email, phone) values ('Griffie Chantrell', 'gchantrell18@flavors.me', '+1 650 845 2297');
insert into Partner (name, email, phone) values ('Fonzie Marchent', 'fmarchent19@163.com', '+62 833 919 9819');
insert into Partner (name, email, phone) values ('Remus Brannan', 'rbrannan1a@so-net.ne.jp', '+86 245 357 3335');
insert into Partner (name, email, phone) values ('Nerita Bigley', 'nbigley1b@goo.gl', '+351 902 590 0477');
insert into Partner (name, email, phone) values ('Annis Edmonston', 'aedmonston1c@shinystat.com', '+66 318 815 8725');
insert into Partner (name, email, phone) values ('Jennilee Danev', 'jdanev1d@kickstarter.com', '+58 557 203 8827');
insert into Partner (name, email, phone) values ('Ryun Doidge', 'rdoidge1e@gravatar.com', '+62 604 328 2283');
insert into Partner (name, email, phone) values ('Jed Calafate', 'jcalafate1f@theglobeandmail.com', '+33 390 909 3516');
insert into Partner (name, email, phone) values ('Teriann Calafato', 'tcalafato1g@omniture.com', '+260 189 304 4519');
insert into Partner (name, email, phone) values ('Larina Anneslie', 'lanneslie1h@scribd.com', '+86 156 599 9416');
insert into Partner (name, email, phone) values ('Evanne Merrin', 'emerrin1i@abc.net.au', '+352 363 561 8153');
insert into Partner (name, email, phone) values ('Adah Brangan', 'abrangan1j@squidoo.com', '+30 496 791 6480');
insert into Partner (name, email, phone) values ('Fanchon Coche', 'fcoche1k@cloudflare.com', '+63 338 500 0685');
insert into Partner (name, email, phone) values ('Neale Brummell', 'nbrummell1l@dyndns.org', '+960 370 378 9642');
insert into Partner (name, email, phone) values ('Kaja Marczyk', 'kmarczyk1m@technorati.com', '+358 717 462 6033');
insert into Partner (name, email, phone) values ('Christopher Marflitt', 'cmarflitt1n@google.ru', '+62 668 563 1449');
insert into Partner (name, email, phone) values ('Helena Wyldes', 'hwyldes1o@boston.com', '+55 238 493 2739');
insert into Partner (name, email, phone) values ('Harv Mabon', 'hmabon1p@twitpic.com', '+7 808 642 8315');
insert into Partner (name, email, phone) values ('Emlyn Jennins', 'ejennins1q@xing.com', '+33 466 807 0208');
insert into Partner (name, email, phone) values ('Chantal Hodgins', 'chodgins1r@sciencedirect.com', '+86 477 880 4646');
insert into Partner (name, email, phone) values ('Angele Morteo', 'amorteo1s@webmd.com', null);
insert into Partner (name, email, phone) values ('Averell Kausche', 'akausche1t@nytimes.com', null);
insert into Partner (name, email, phone) values ('Lurleen Tribble', 'ltribble1u@virginia.edu', '+57 416 423 4634');
insert into Partner (name, email, phone) values ('Rosina Lovejoy', 'rlovejoy1v@house.gov', '+60 241 660 1020');
insert into Partner (name, email, phone) values ('Dulsea Speer', 'dspeer1w@people.com.cn', '+358 391 414 9590');
insert into Partner (name, email, phone) values ('Ad Edgeler', 'aedgeler1x@amazon.de', null);
insert into Partner (name, email, phone) values ('Aleta Jenicek', 'ajenicek1y@behance.net', '+380 401 460 4244');
insert into Partner (name, email, phone) values ('Tully Nardi', 'tnardi1z@opera.com', '+359 555 930 2407');
insert into Partner (name, email, phone) values ('Ezra Lesek', 'elesek20@drupal.org', '+62 238 578 5335');
insert into Partner (name, email, phone) values ('Dorise Brogden', 'dbrogden21@arstechnica.com', '+62 322 520 1178');
insert into Partner (name, email, phone) values ('Duane Oneile', 'doneile22@ca.gov', '+381 773 334 0789');
insert into Partner (name, email, phone) values ('Stanislaw Eskrigg', 'seskrigg23@npr.org', '+225 584 331 3321');
insert into Partner (name, email, phone) values ('Kelley Ximenez', 'kximenez24@telegraph.co.uk', null);
insert into Partner (name, email, phone) values ('Aldous Smittoune', 'asmittoune25@webs.com', '+57 669 713 9284');
insert into Partner (name, email, phone) values ('Wilma Wedge', 'wwedge26@fastcompany.com', '+62 255 942 6077');
insert into Partner (name, email, phone) values ('Peggy Gierok', 'pgierok27@mtv.com', '+7 623 513 8287');
insert into Partner (name, email, phone) values ('Shepperd Gibbetts', 'sgibbetts28@howstuffworks.com', '+56 883 107 9794');
insert into Partner (name, email, phone) values ('Zorah Lyall', 'zlyall29@mediafire.com', '+94 993 763 9352');
insert into Partner (name, email, phone) values ('Hollyanne Duchart', 'hduchart2a@usgs.gov', null);
insert into Partner (name, email, phone) values ('Reynolds Bligh', 'rbligh2b@columbia.edu', null);
insert into Partner (name, email, phone) values ('Delora Pilbury', 'dpilbury2c@nymag.com', null);
insert into Partner (name, email, phone) values ('Lincoln Smieton', 'lsmieton2d@newyorker.com', null);
insert into Partner (name, email, phone) values ('Maury Robbins', 'mrobbins2e@hatena.ne.jp', '+62 923 206 1659');
insert into Partner (name, email, phone) values ('Micheal Perrington', 'mperrington2f@omniture.com', '+48 612 651 5164');
insert into Partner (name, email, phone) values ('Daven Smallpeice', 'dsmallpeice2g@nsw.gov.au', '+48 550 669 3462');
insert into Partner (name, email, phone) values ('Berri Flanner', 'bflanner2h@dmoz.org', '+55 530 288 5617');
insert into Partner (name, email, phone) values ('Constancia Easdon', 'ceasdon2i@scribd.com', null);
insert into Partner (name, email, phone) values ('Margarita Tethcote', 'mtethcote2j@howstuffworks.com', '+7 355 514 8325');
insert into Partner (name, email, phone) values ('Ardeen Spendley', 'aspendley2k@booking.com', '+46 276 458 0505');
insert into Partner (name, email, phone) values ('Anne Tucker', 'atucker2l@cocolog-nifty.com', '+86 356 357 5392');
insert into Partner (name, email, phone) values ('Grata Haughey', 'ghaughey2m@rediff.com', '+261 555 268 6615');
insert into Partner (name, email, phone) values ('Paddie Saberton', 'psaberton2n@washingtonpost.com', '+62 722 684 4814');
insert into Partner (name, email, phone) values ('Dolorita Maxted', 'dmaxted2o@hugedomains.com', '+86 634 951 2802');
insert into Partner (name, email, phone) values ('Scarlett Thomassin', 'sthomassin2p@trellian.com', '+382 181 738 6836');
insert into Partner (name, email, phone) values ('Bethena Philipot', 'bphilipot2q@prnewswire.com', '+55 186 261 0733');
insert into Partner (name, email, phone) values ('Aristotle Denman', 'adenman2r@irs.gov', '+420 760 610 4234');
insert into Partner (name, email, phone) values ('Elladine Liggons', 'eliggons2s@issuu.com', '+63 387 599 6223');
insert into Partner (name, email, phone) values ('Aldous De Gregoli', 'ade2t@blogtalkradio.com', null);
insert into Partner (name, email, phone) values ('Vinny Wisniowski', 'vwisniowski2u@purevolume.com', null);
insert into Partner (name, email, phone) values ('Garold Astles', 'gastles2v@rakuten.co.jp', '+33 453 746 7793');
insert into Partner (name, email, phone) values ('Alica Orbell', 'aorbell2w@bing.com', '+63 113 103 0841');
insert into Partner (name, email, phone) values ('Woodman Tadlow', 'wtadlow2x@photobucket.com', '+32 476 921 5414');
insert into Partner (name, email, phone) values ('Heath Hadrill', 'hhadrill2y@ihg.com', '+86 768 802 7424');
insert into Partner (name, email, phone) values ('Brooke Huggon', 'bhuggon2z@google.co.jp', '+995 423 806 9097');
insert into Partner (name, email, phone) values ('Cristian Kruschev', 'ckruschev30@lulu.com', '+7 875 780 8249');
insert into Partner (name, email, phone) values ('Benny Suffe', 'bsuffe31@statcounter.com', null);
insert into Partner (name, email, phone) values ('Parsifal Glover', 'pglover32@ted.com', '+970 827 425 6804');
insert into Partner (name, email, phone) values ('Beatrix Iaduccelli', 'biaduccelli33@hp.com', '+86 915 786 9558');
insert into Partner (name, email, phone) values ('Mommy Habeshaw', 'mhabeshaw34@tamu.edu', '+86 474 760 7050');
insert into Partner (name, email, phone) values ('Monti Kyles', 'mkyles35@xrea.com', null);
insert into Partner (name, email, phone) values ('Prinz Welberry', 'pwelberry36@over-blog.com', '+355 140 565 9053');
insert into Partner (name, email, phone) values ('Nonie Burnyeat', 'nburnyeat37@acquirethisname.com', '+81 167 218 7372');
insert into Partner (name, email, phone) values ('Lucine Le Grice', 'lle38@umn.edu', '+420 960 681 6807');
insert into Partner (name, email, phone) values ('Courtney Moy', 'cmoy39@sitemeter.com', '+7 207 144 3900');
insert into Partner (name, email, phone) values ('Kathie Hall-Gough', 'khallgough3a@nih.gov', '+62 293 641 7662');
insert into Partner (name, email, phone) values ('Beatriz Hush', 'bhush3b@gov.uk', '+84 441 731 1134');
insert into Partner (name, email, phone) values ('Ariella Fitzroy', 'afitzroy3c@photobucket.com', '+994 865 231 5977');
insert into Partner (name, email, phone) values ('Yalonda Lejeune', 'ylejeune3d@networkadvertising.org', '+86 333 674 5075');
insert into Partner (name, email, phone) values ('Marion Spores', 'mspores3e@fotki.com', '+1 901 459 0799');
insert into Partner (name, email, phone) values ('Imojean Olyunin', 'iolyunin3f@cnet.com', '+81 301 567 9211');
insert into Partner (name, email, phone) values ('Moen-Schiller', 'hborham0@artisteer.com', '+351 780 722 3016');
insert into Partner (name, email, phone) values ('Pfeffer, Towne and Ruecker', 'ssaladine1@example.com', null);
insert into Partner (name, email, phone) values ('Trantow-Leannon', 'esproston2@ibm.com', '+46 892 867 5908');
insert into Partner (name, email, phone) values ('McCullough, Bayer and Rowe', 'jtebbit3@yahoo.com', '+33 149 651 2249');
insert into Partner (name, email, phone) values ('Goodwin-Rowe', 'eortells4@ehow.com', '+234 547 397 6712');
insert into Partner (name, email, phone) values ('Cruickshank, Monahan and Simonis', 'kmogg5@prlog.org', '+33 588 431 6552');
insert into Partner (name, email, phone) values ('Von-Gusikowski', 'whallum6@jiathis.com', null);
insert into Partner (name, email, phone) values ('Pfannerstill, Christiansen and Ritchie', 'bmyers7@miitbeian.gov.cn', '+86 828 824 8908');
insert into Partner (name, email, phone) values ('Homenick, Langosh and Hermiston', 'sbunstone8@irs.gov', '+58 736 134 5269');
insert into Partner (name, email, phone) values ('Hammes, Turcotte and MacGyver', 'kkunisch9@webs.com', '+66 890 705 9364');
insert into Partner (name, email, phone) values ('Robel Inc', 'rcranagea@shop-pro.jp', '+86 282 835 8782');
insert into Partner (name, email, phone) values ('Abernathy Inc', 'jwensleyb@dropbox.com', '+86 129 319 1422');
insert into Partner (name, email, phone) values ('Olson and Sons', 'dsilkstonc@census.gov', null);
insert into Partner (name, email, phone) values ('McLaughlin-Gerhold', 'bmeneuxd@php.net', '+254 931 106 3087');
insert into Partner (name, email, phone) values ('Swift, Krajcik and Streich', 'jgohiere@macromedia.com', '+33 876 385 9411');
insert into Partner (name, email, phone) values ('Lebsack and Sons', 'cabreyf@barnesandnoble.com', '+33 391 723 6198');
insert into Partner (name, email, phone) values ('Osinski LLC', 'ycorkelg@cpanel.net', '+54 276 274 3974');
insert into Partner (name, email, phone) values ('Sipes, Christiansen and Reinger', 'rrowesbyh@skype.com', '+970 400 116 8858');
insert into Partner (name, email, phone) values ('Thiel LLC', 'cdresselli@chicagotribune.com', '+98 754 282 1686');
insert into Partner (name, email, phone) values ('Kuphal Group', 'ijentgensj@spotify.com', '+86 241 781 0467');
insert into Partner (name, email, phone) values ('Bernier, Gutkowski and Bode', 'dmucillok@samsung.com', '+55 669 330 1412');
insert into Partner (name, email, phone) values ('Harris Inc', 'kstairl@craigslist.org', null);
insert into Partner (name, email, phone) values ('Labadie-Mueller', 'qkornesm@webnode.com', '+66 851 737 9830');
insert into Partner (name, email, phone) values ('Carter, Harvey and Gislason', 'cdraycottn@mapy.cz', '+46 569 913 0982');
insert into Partner (name, email, phone) values ('Nitzsche, Hagenes and Douglas', 'gbiddello@mapy.cz', null);
insert into Partner (name, email, phone) values ('Ondricka, Rowe and O''Reilly', 'severp@time.com', '+86 753 508 9960');
insert into Partner (name, email, phone) values ('Jones, Nader and MacGyver', 'gmccourtq@clickbank.net', '+55 276 440 0025');
insert into Partner (name, email, phone) values ('Swift, Mraz and Renner', 'ctaskerr@blogger.com', '+33 206 229 9690');
insert into Partner (name, email, phone) values ('Weissnat and Sons', 'rroswarns@scientificamerican.com', '+55 287 904 8048');
insert into Partner (name, email, phone) values ('VonRueden Inc', 'mcransont@reverbnation.com', '+502 793 508 8926');
insert into Partner (name, email, phone) values ('Effertz Inc', 'elavericku@joomla.org', '+98 483 519 0547');
insert into Partner (name, email, phone) values ('Gerhold-Heidenreich', 'clanceterv@icq.com', '+86 670 230 2220');
insert into Partner (name, email, phone) values ('Zemlak-Dickinson', 'scleoburyw@china.com.cn', '+55 345 461 3146');
insert into Partner (name, email, phone) values ('Barrows-Kozey', 'csteptoex@webs.com', '+7 744 296 9210');
insert into Partner (name, email, phone) values ('Leffler-Bernhard', 'cfletty@goo.gl', null);
insert into Partner (name, email, phone) values ('Cummings-Thompson', 'sdunhillz@globo.com', '+962 430 572 1842');
insert into Partner (name, email, phone) values ('Runolfsdottir, Bechtelar and Macejkovic', 'cburgum10@addtoany.com', '+55 602 835 5325');
insert into Partner (name, email, phone) values ('Ernser LLC', 'aharmeston11@fema.gov', '+27 333 115 8750');
insert into Partner (name, email, phone) values ('Torphy, Oberbrunner and Littel', 'idorken12@cafepress.com', '+47 651 892 2128');
insert into Partner (name, email, phone) values ('Schuster, Mitchell and Shields', 'vjackways13@simplemachines.org', null);
insert into Partner (name, email, phone) values ('Hessel Inc', 'rvanyarkin14@cpanel.net', '+1 713 194 0864');
insert into Partner (name, email, phone) values ('Johnson, Schroeder and Turner', 'nskivington15@gov.uk', '+420 324 460 7262');
insert into Partner (name, email, phone) values ('Simonis-Keeling', 'eelphinstone16@usgs.gov', '+51 601 727 7441');
insert into Partner (name, email, phone) values ('Maggio, Jacobson and Baumbach', 'cspyer17@360.cn', '+62 554 737 7516');
insert into Partner (name, email, phone) values ('Schroeder, Kling and Weimann', 'kminghi18@earthlink.net', '+86 755 973 4546');
insert into Partner (name, email, phone) values ('Leffler Group', 'krotchell19@seesaa.net', '+62 687 275 2392');
insert into Partner (name, email, phone) values ('Harvey-Schuppe', 'dgilding1a@pagesperso-orange.fr', '+86 953 480 3901');
insert into Partner (name, email, phone) values ('Rau, Schroeder and Murray', 'lbruyntjes1b@ted.com', '+86 741 300 8896');
insert into Partner (name, email, phone) values ('Homenick LLC', 'cfaughey1c@soundcloud.com', '+55 828 756 3666');
insert into Partner (name, email, phone) values ('Beer-Brown', 'ggraith1d@parallels.com', '+62 395 172 5639');
insert into Partner (name, email, phone) values ('Kertzmann-Jaskolski', 'lsarton1e@sphinn.com', '+63 807 263 6034');
insert into Partner (name, email, phone) values ('Koss-Rohan', 'rbendixen1f@fc2.com', '+86 903 665 5069');
insert into Partner (name, email, phone) values ('Kemmer and Sons', 'cmcvie1g@ow.ly', '+1 547 819 7049');
insert into Partner (name, email, phone) values ('Klein, Heathcote and Strosin', 'sgallahue1h@dailymotion.com', null);
insert into Partner (name, email, phone) values ('Maggio-Shields', 'lpiatkowski1i@netlog.com', '+98 399 647 6266');
insert into Partner (name, email, phone) values ('Schroeder Group', 'rhachard1j@dot.gov', '+355 812 320 3097');
insert into Partner (name, email, phone) values ('Waters-Runte', 'apassler1k@51.la', null);
insert into Partner (name, email, phone) values ('Oberbrunner, Casper and Murphy', 'torteau1l@blogtalkradio.com', '+234 936 984 0919');

SELECT * FROM Partner;